# Imports
import requests
import time
import random
import datetime
import csv
import os
from colorama import Fore, Style, init
from tabulate import tabulate
from fpdf import FPDF
from jinja2 import Template

init(autoreset=True)

PLATFORMS = [
    {"name": "Instagram", "url": "https://www.instagram.com/{}"},
    {"name": "Twitter", "url": "https://www.x.com/{}"},
    {"name": "Facebook", "url": "https://www.facebook.com/{}"},
    {"name": "YouTube", "url": "https://www.youtube.com/@{}"},
    {"name": "Snapchat", "url": "https://story.snapchat.com/@{}"},
    {"name": "Spotify", "url": "https://open.spotify.com/user/{}"},
    {"name": "Pinterest", "url": "https://www.pinterest.com/{}"},
    {"name": "Reddit", "url": "https://www.reddit.com/user/{}"},
    {"name": "Tinder", "url": "https://www.tinder.com/@{}"},
    {"name": "Github", "url": "https://www.github.com/{}"},
    {"name": "LinkedIn", "url": "https://www.linkedin.com/in/{}"},
    {"name": "TikTok", "url": "https://www.tiktok.com/@{}"},
    {"name": "Medium", "url": "https://medium.com/@{}"},
    {"name": "Tumblr", "url": "https://{}.tumblr.com/"},
    {"name": "Vimeo", "url": "https://vimeo.com/{}"},
    {"name": "Twitch", "url": "https://www.twitch.tv/{}"},
    {"name": "AskFM", "url": "https://ask.fm/{}"},
    {"name": "Flickr", "url": "https://www.flickr.com/people/{}"},
    {"name": "DeviantArt", "url": "https://www.deviantart.com/{}"},
    {"name": "SoundCloud", "url": "https://soundcloud.com/{}"},
]

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Username OSINT Report for {{ username }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #222; }
        .container { background: #fff; max-width: 900px; margin: 40px auto; padding: 40px; border-radius: 20px; box-shadow: 0 20px 40px rgba(0,0,0,0.1); }
        .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #667eea; }
        .header h1 { color: #667eea; font-size: 2.5em; margin-bottom: 10px; }
        .header .subtitle { color: #666; font-size: 1.1em; }
        .section { margin-top: 40px; padding: 25px; border-radius: 15px; box-shadow: 0 5px 15px rgba(0,0,0,0.08); }
        .summary { background: linear-gradient(135deg, #4CAF50, #8BC34A); color: #fff; padding: 25px; border-radius: 15px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 15px; background: #fff; border-radius: 10px; overflow: hidden; box-shadow: 0 5px 15px rgba(0,0,0,0.1); }
        .table th, .table td { border: 1px solid #eee; padding: 12px; text-align: left; }
        .table th { background: #667eea; color: #fff; font-weight: 600; }
        .table tr:nth-child(even) { background: #f8f9fa; }
        .found { color: #4CAF50; font-weight: bold; }
        .notfound { color: #f44336; font-weight: bold; }
        .link { color: #667eea; text-decoration: none; font-weight: 600; }
        .link:hover { text-decoration: underline; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 2px solid #eee; color: #666; }
        @media (max-width: 768px) { .container { margin: 20px; padding: 20px; } .header h1 { font-size: 2em; } }
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>👤 Username OSINT Report</h1>
        <div class="subtitle">Generated by ScayNum - Advanced Username Intelligence</div>
    </div>
    <div class="section">
        <h2>🔎 Username Searched:</h2>
        <div class="summary">
            <strong>Username:</strong> {{ username }}<br>
            <strong>Visibility Score:</strong> {{ visibility_score }} / 100<br>
            <strong>Risk Level:</strong> <span class="{{ risk_level }}">{{ risk_level.upper() }}</span><br>
            <strong>Recommendations:</strong> {{ recommendations }}
        </div>
    </div>
    <div class="section">
        <h2>🌐 Platform Results</h2>
        <table class="table">
            <tr><th>Platform</th><th>Status</th><th>Profile Link</th></tr>
            {% for result in results %}
            <tr>
                <td>{{ result.platform }}</td>
                <td class="{{ 'found' if result.found else 'notfound' }}">{{ 'Found' if result.found else 'Not Found' }}</td>
                <td>{% if result.found %}<a href="{{ result.url }}" class="link" target="_blank">{{ result.url }}</a>{% else %}-{% endif %}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="footer">
        <strong>Report generated at:</strong> {{ now }}<br>
        <strong>Tool:</strong> ScayNum by Scayar | <a href="https://scayar.com" class="link">https://scayar.com</a>
    </div>
</div>
</body>
</html>
'''

def create_user_folder(username):
    safe_username = username.replace(' ', '_')
    folder_name = f"username_{safe_username}_results"
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)
    return folder_name

def assess_risk_level(found_count, total):
    score = int((found_count / total) * 100)
    if score >= 60:
        return score, 'high'
    elif score >= 30:
        return score, 'medium'
    else:
        return score, 'low'

def generate_recommendations(risk_level):
    if risk_level == 'high':
        return "HIGH: Username is highly visible across platforms. Consider using unique usernames for privacy."
    elif risk_level == 'medium':
        return "MEDIUM: Username is moderately visible. Review privacy settings on found platforms."
    else:
        return "LOW: Username has low visibility. Good for privacy."

class SearchUsername:
    def __init__(self, username) -> None:
        self.username = username
        self.lookup()

    def lookup(self):
        print(Fore.CYAN + f"\n👤 Starting Username OSINT for: {self.username}")
        user_folder = create_user_folder(self.username)
        print(Fore.GREEN + f"📁 Created folder: {user_folder}")
        results = []
        found_count = 0
        total = len(PLATFORMS)
        for platform in PLATFORMS:
            url = platform["url"].format(self.username)
            try:
                headers = {"User-Agent": "Mozilla/5.0"}
                resp = requests.get(url, headers=headers, timeout=8)
                found = resp.status_code == 200 and self.username.lower() in resp.text.lower()
                if found:
                    found_count += 1
                    print(Fore.GREEN + f"[+] {platform['name']}: Found -> {url}")
                else:
                    print(Fore.RED + f"[-] {platform['name']}: Not Found")
            except Exception as e:
                found = False
                print(Fore.YELLOW + f"[?] {platform['name']}: Error - {e}")
            results.append({
                "platform": platform["name"],
                "url": url,
                "found": found
            })
            time.sleep(random.uniform(0.5, 1.2))
        visibility_score, risk_level = assess_risk_level(found_count, total)
        recommendations = generate_recommendations(risk_level)
        self.display_results(results, visibility_score, risk_level, recommendations)
        self.generate_reports(user_folder, results, visibility_score, risk_level, recommendations)
        print(Fore.LIGHTGREEN_EX + f"\n📁 All files saved in folder: {user_folder}")
        print(Fore.LIGHTGREEN_EX + "\n========== Username OSINT Completed! ==========")

    def display_results(self, results, visibility_score, risk_level, recommendations):
        print(Fore.MAGENTA + "\n========== Username OSINT Results ==========")
        print(Fore.CYAN + f"Username: {self.username}")
        print(Fore.CYAN + f"Visibility Score: {visibility_score}/100")
        print(Fore.CYAN + f"Risk Level: {risk_level.upper()}")
        print(Fore.CYAN + f"Recommendations: {recommendations}")
        print(tabulate([
            [r['platform'], 'Found' if r['found'] else 'Not Found', r['url'] if r['found'] else '-']
            for r in results
        ], headers=["Platform", "Status", "Profile Link"], tablefmt="fancy_grid"))

    def generate_reports(self, user_folder, results, visibility_score, risk_level, recommendations):
        # CSV
        csv_filename = os.path.join(user_folder, f"username_{self.username}_osint.csv")
        with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(["Platform", "Status", "Profile Link"])
            for r in results:
                writer.writerow([r['platform'], 'Found' if r['found'] else 'Not Found', r['url'] if r['found'] else '-'])
        print(Fore.GREEN + f"📊 CSV report saved as {csv_filename}")
        # PDF
        try:
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", size=12)
            pdf.cell(200, 10, txt=f"Username OSINT Report: {self.username}", ln=True, align='C')
            pdf.cell(200, 10, txt=f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
            pdf.cell(200, 10, txt="", ln=True)
            pdf.cell(200, 10, txt=f"Visibility Score: {visibility_score}/100", ln=True)
            pdf.cell(200, 10, txt=f"Risk Level: {risk_level.upper()}", ln=True)
            pdf.cell(200, 10, txt=f"Recommendations: {recommendations}", ln=True)
            pdf.cell(200, 10, txt="", ln=True)
            pdf.cell(200, 10, txt="Platform Results:", ln=True)
            for r in results:
                status = 'Found' if r['found'] else 'Not Found'
                pdf.cell(200, 10, txt=f"{r['platform']}: {status}", ln=True)
                if r['found']:
                    pdf.cell(200, 10, txt=f"  {r['url']}", ln=True)
            pdf_path = os.path.join(user_folder, f"username_{self.username}_osint.pdf")
            pdf.output(pdf_path)
            print(Fore.GREEN + f"📄 PDF report saved as {pdf_path}")
        except Exception as e:
            print(Fore.RED + f"❌ PDF generation failed: {e}")
        # HTML
        try:
            html = Template(HTML_TEMPLATE).render(
                username=self.username,
                results=results,
                visibility_score=visibility_score,
                risk_level=risk_level,
                recommendations=recommendations,
                now=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            )
            html_path = os.path.join(user_folder, f"username_{self.username}_osint.html")
            with open(html_path, "w", encoding="utf-8") as f:
                f.write(html)
            print(Fore.GREEN + f"🌐 HTML report saved as {html_path}")
        except Exception as e:
            print(Fore.RED + f"❌ HTML generation failed: {e}")
